### ISSUE TITLE
Go to top button not showing

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#114]
v2.0.1 store version is not showing the go to top button in the listview scrolling

**Comment by bartlannoeye** [comment]
Cannot reproduce in both debug and release config on the latest source code, please verify as well.

**Comment by bartlannoeye** [comment]
Further research: shows on touch, not with mouse

**Comment by Depechie** [comment]
My Win Phone 10 mobile updated the WinRT version to UWP version, not seeing the move to top button :/

**Comment by Depechie** [comment]
Bug still there on v2.1!
BUT found out it is being drawn and active, only not visible :/
So if you scroll down and tap in low right corner the list will go up ( function of the button ), only the user can't tell it's there, because it is invisible.
