### ISSUE TITLE
Unable to edit activities

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#118]
Currently it is unclear for the user that he has to select an item from the gear drop down, when he want's to edit some info of a given activity.

We should allow unselected state with the edit API

**Comment by bartlannoeye** [comment]
Next to that, if an existing bike/shoes is selected, this should be preselected when going into edit mode.

**Comment by Depechie** [comment]
Not sure we can get the default from the API, or even the gear info, need to look that up... Also we should add more settings options on the settings page to allow people to indicate what gear should be preselected for each activity type.
