### ISSUE TITLE
What's new popup

### ISSUE THREAD

**Issue by bartlannoeye** [AppCreativity/Kliva#120]
Popup to inform user (only) in case of important changes.
e.g. v2.1.2+: log out for token

**Comment by Depechie** [comment]
Was maybe thinking of auto opening settings page with what is new tab on first time use of app after version update... what do you think?

**Comment by Depechie** [comment]
Problem with that approach, we need to embed the info we want users to read at release time.
So this can't be 'triggered' remotely.

Maybe we could try using https://pages.github.com and create a release page for each release?
Or maybe load up info json files to the GitHub repo and scan for those at app start?
So if such a json file is present we show a dialog at app startup showing the info...? But how many times do we present this information, in other words how to track this?

**Comment by PieEatingNinjas** [comment]
`But how many times do we present this information, in other words how to track this?`
For the "what's new" video page in Yelo, we just wrote the last version the user had seen to the local settings. That way we could determine whether to show this page or not.

So what we could do for Kliva is maybe the following:
- at startup look at the current version of the app (Package.Current)
- look in local settings if the version we saved last is equal to the current version
- if not -> get json file (or GitHub page or whatever) and display it to user
- save current version of app in local settings

You could also argue to put this in Roaming settings so a user only sees this info on startup once across multiple devices. 

Give me a shout if you'd like me to implement this.

**Comment by Depechie** [comment]
The scenario with saving current version and checking it with release version is already available on the Information branch. Maybe check that to see if it is good or not. It will just present what's new, that info is given with a packaged json file...  But that still gives no solution for remote information presenting.

**Comment by PieEatingNinjas** [comment]
I see, will take a look at the implementation.
So the issue here is that you don't want to embed a json file with the release information but store this remotely?

**Comment by Depechie** [comment]
No, would love to have the remote info as extra, if possible... so general what's new like we have now and also present information to the user if there is a remote file available ( and that remote one should be checked each time the app starts )

**Comment by Depechie** [comment]
Only thing not so sure of, how to handle that remote scenario... so any input welcome :)

**Comment by PieEatingNinjas** [comment]
GiHub Pages should do the trick for that, I think. But not sure if they are 'designed' for that kind of purpose...  Give your pages an 'intelligent' name ([AppVersion].json). Do a request to that page. If 404, just ignore it, else display the information.
Another possibility might be Easy Tables of Visual Studio Mobile Center... But that might be a bit of overkill...

**Comment by Depechie** [comment]
Need to investigate more, but seems possible to generate them too... !

https://github.com/IowaCodeCamp/iowacodecamp.github.io
https://github.com/IowaCodeCamp/iowacodecamp.github.io/blob/master/sessions.json
http://iowacodecamp.github.io/sessions.json
