### ISSUE TITLE
Segment Leaderboards

### ISSUE THREAD

**Issue by SteveDrakey** [AppCreativity/Kliva#126]
It would be nice to be able to tap a segment and see the leaderboards such as

https://www.strava.com/segments/9671105?filter=following

**Comment by bartlannoeye** [comment]
Great suggestion, we'll have to look if this is possible with the public APIs.

**Comment by Depechie** [comment]
@SteveDrakey question, if I click on your suggested link, I see the overall leaderboard. But the link has a filter 'following" does this mean you would only see the leaderboard of the selected segment of only the people you are following?

**Comment by SteveDrakey** [comment]
Yes, 'following' adds a filter. You can configure Strava to default to a filter. 

I have worked with the Strava API and I am sure that you can view segment leader boards via the API. 

https://strava.github.io/api/v3/segments/

I have used this in the past

https://github.com/inexcitus/stravadotnet

It has some wrappers to the Segment API, not sure how well it would work with UWP though and your framework, but it could be used a reference if you prefer to look at code rather than docs ;)

**Comment by Depechie** [comment]
Yeah our code is based on that .net api too :)
I added a Leaderboards tab on the detail segment screen, it will show the top 10 leaders for that segment ( overall ) and all the leaders you are following.
So 2 separate lists...

When the PR get's merged to the main repo, we'll try to do an app update!
