### ISSUE TITLE
(Not a project issue) Kliva removed from the store?

### ISSUE THREAD

**Issue by wokhan** [AppCreativity/Kliva#130]
Hi everybody,
I was about to reinstall Kliva on my device but I cannot find it anymore... Was it removed because of GDPR or was it intentional?
In the first case, do you think it will come back?
If not I can rebuild the package locally of course but I'm also thinking about other users :-)
Thank you for this great app!

**Comment by bartlannoeye** [comment]
Hey @wokhan 

We've had privacy issues for over half a year now, even before GDPR. Next to that Strava is cutting on its public APIs, taking away functionality already implemented (while in an ideal world, we would get even more like uploading images).

So looking at it right now, chances are slim that we will continue our battle to get it back in the store, certainly for phone. If we bring it back to Windows, it would be a "readonly" application.

**Comment by bartlannoeye** [comment]
Since Strava did cut even more APIs, we're closing down Kliva and this repository. For more info, please check the readme.
