### ISSUE TITLE
Different format for times on user statistics

### ISSUE THREAD

**Issue by igoramadas** [AppCreativity/Kliva#17]
Hi,

on the user stats page it displays total times in dd:hh:mm format. So if I cycled for 30 hours it will show 1:06:00, which is basically quite confusing as it could also mean 1 hour and 6 minutes.

Maybe you should "humanize" these values with a postfix, like 4d 10h 3m which is obvious and easy to understand.

Thx!

**Comment by Depechie** [comment]
Hey Igor,

That's a good point!
I'll take a look at how we could change it to something more readable.

Thanks for using the app :)

Greets
Glenn

**Comment by igoramadas** [comment]
Hi Glenn,

just got the latest update and it looks much better now. Good work!

But depending on the combination of totals, the string might get too long and it will cut the last bit out. Check the image attached (the "all time / moving time"). A slightly smaller font will do the trick :-)

![wp_ss_20150518_0001](https://cloud.githubusercontent.com/assets/1576674/7683500/e24e0d40-fd7f-11e4-8b41-76ef5c42c0e1.png)

**Comment by Depechie** [comment]
Ha good catch!
