### ISSUE TITLE
Provide 'empty' Activity detail screen

### ISSUE THREAD

**Issue by bartlannoeye** [AppCreativity/Kliva#26]
Right now the Activity detail screen already has the text controls set for all the statistics, without an activity being selected. This looks rather odd, but an empty screen isn't perfect either as this doesn't invite to select an activity.

A possible solution would be to show a blurred detail screen to invite the selection of an activity. Issue: this can't be an image if we want it to scale perfect to the real screen on each device.

![image](https://cloud.githubusercontent.com/assets/5115577/13285727/8a2be80c-dafc-11e5-92db-5e9a72743b83.png)

**Comment by Depechie** [comment]
Would rather go with the 'show nothing' option, like the Microsoft UWP mail app. So as long as you didn't select any activity in the activity feed list, the right side should be empty. We could also use this to show nice cycling pictures when nothing is selected...

Technically this means binding the ActivityDetailControl it's visibility to the SelectedActivity property of the viewmodel.
