### ISSUE TITLE
Improve navigation flow

### ISSUE THREAD

**Issue by timheuer** [AppCreativity/Kliva#27]
Add an icon to view switcher for activity view
Fix navigation to what Jake is doing in his sample
Build empty views on view switcher hook up switching

**Comment by JasterAtMicrosoft** [comment]
I'm looking at this. Is there a reason certain page types do not show the side navigation pane? (SidePaneViewModel.cs:146.) This seems like an anti-pattern as it makes the harder for the user to navigate in between the views and most UWP apps always keep the navigation bar available.

**Comment by Depechie** [comment]
Nope, at the time I thought it would make more sense to use the back button. But I have no problem to let the navigationbar stay visible all the time! Only the login page should not have it I guess.
