### ISSUE TITLE
Improve activity list performance and loading

### ISSUE THREAD

**Issue by timheuer** [AppCreativity/Kliva#28]
Improve the overall performance of activity list feed

**Comment by Depechie** [comment]
Currently in the StravaService Class we have a GetActivitySummaryRelationsAsync method that will do a Task.WhenAll() with 2 tasks. One of them is to load photo's maybe we can change that to First() to speed up the Async /await process?

**Comment by timheuer** [comment]
My plan here is to implement the x:Phase capabilities to see how that changes things.  As we hook up more future stuff :-) we'll likely need to hook into the render pipeline anyway, so it's less about the data, more about the drawing.

**Comment by Depechie** [comment]
Ha, good!!
