### ISSUE TITLE
Add static Map to activity feed list

### ISSUE THREAD

**Issue by timheuer** [AppCreativity/Kliva#29]

**Comment by Depechie** [comment]
Due to perfomance issues we have to reevaluate this :(

**Comment by timheuer** [comment]
Which perf issues are you seeing?

**Comment by Depechie** [comment]
On phone the list is 'visibly' waiting for the downloads to finish before rendering it seems.
Also when loading a lot of items and then pressing the go to top button, the listview can't keep up with the rendering ( even though everything is already cached ), when tracking with VS profiler I'm seeing a lot of Renderer timings.

Any guides on this would be most welcome ( maybe on slack channel )

**Comment by bartlannoeye** [comment]
Tim's implementation on the alcatraz branch looked fast to me.

**Comment by Depechie** [comment]
On phone? On desktop there is indeed no problem...
By the way the video is also with BackgroundDownloader version ( so same as Alcatraz branch )

**Comment by Depechie** [comment]
We were still using bitmap.SetSource instead of bitmap.SetSourceAsync, so that was why the UI thread was still blocking when loading! So that part is fixed.
The fast scrolling is still a minor point we could address in future if needed...
