### ISSUE TITLE
Activities out of order

### ISSUE THREAD

**Issue by bartlannoeye** [AppCreativity/Kliva#48]
The current cache returns activities out of order compared to the site (but in correct timestamp order according to timezones):
App
![image](https://cloud.githubusercontent.com/assets/5115577/13612746/6f9c4b40-e569-11e5-9dba-7e6ff2cd6754.png)

Site
![image](https://cloud.githubusercontent.com/assets/5115577/13612760/858f47e0-e569-11e5-8a6a-f382d351ef8b.png)

**Comment by bartlannoeye** [comment]
It looks like this is the same as in our WP8 app. So the question is: do we want to try and reproduce the incorrect order of Strava.com ? I'd think not.

**Comment by Depechie** [comment]
Not sure, Strava website is wrong... official Strava app has same order as website :/

**Comment by bartlannoeye** [comment]
After some extra research I found the API returns activities ordered by start time, while the site shows ordered by end time (so longer running activities are higher on the list). I'll implement the option to choose between both and intervene in the result returned to the UI (as in https://github.com/AppCreativity/Kliva/commit/1526da2322ba2858e4fee61495cf04e7efb68d4d)
