### ISSUE TITLE
Loading activities with saved filter settings

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#57]
When you select 'my activities' as active filter and close / reopen the app, you'll get the activity feed of 'my activities'.

But the filter selection on top will not show this, it will point to Show all activities.

Secondly, loading saved activities through this, will no longer show athlete avatars?

![screenshot 31](https://cloud.githubusercontent.com/assets/351693/13828078/02218b18-ebc0-11e5-8614-d9626802b1d7.png)

**Comment by bartlannoeye** [comment]
Part 1 fixed in 563aae6920710941b24e14199c27a4762580800c
Part 2 still open
