### ISSUE TITLE
XamlParseException on loginpage

### ISSUE THREAD

**Issue by EngstromJimmy** [AppCreativity/Kliva#68]
When starting the app on a PC running SDK 14332 I get:
(XamlParseException) Cannot create instance of type 'SamplesCommon.BackDrop' [Line: 77 Position: 13]
The exception is thrown by the LoginPage.
Alcatraz branch

**Comment by bartlannoeye** [comment]
Runs fine on 14342 with the 14332 SDK. Will have to look deeper into this.
