### ISSUE TITLE
Switching filter - clear selection

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#83]
Maybe we should clear the current selected activity if we switch the filter on the activity list.

Bit weird an activity that is no longer in the list is still visible in the detail view.

Currently the ActivitySummary message that is routed from the activity list to the detail view model can't handle null value.
So we need to modify this...

**Comment by PieEatingNinjas** [comment]
Also noticed this but, like you said, there are quite some issues with setting he activity to null.

**Comment by Depechie** [comment]
Nice to have not a must for first store release :)
