### ISSUE TITLE
Extra info for segments

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#84]
When showing list of segments on an activity, would be great to have following extra info
- [x] Speed
- [ ] Average HR

**Comment by bartlannoeye** [comment]
Maybe we should introduce fixed width for this line to have it better aligned.

![image](https://cloud.githubusercontent.com/assets/5115577/19983871/130a72fc-a20c-11e6-8083-b61743d51ca6.png)

Todo:
- Average HR (but rounding logic is in groupitems of detail page > to be refactored)
