### ISSUE TITLE
Activity feed item design

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#91]
The activity feed item design needs some work
- [x] Add kudos icon and count
- [x] Add comments icon and count
- [x] Allign other athletes icon and count with other icons
- [x] Icons should be right bottom alligned ( underneath activity date )

**Comment by PieEatingNinjas** [comment]
@Depechie : could you provide me a quick sketch or something to show how you would like the design to be?

**Comment by Depechie** [comment]
![img_1896](https://cloud.githubusercontent.com/assets/351693/19211760/8f276aac-8d44-11e6-8e7c-e39f43868714.jpg)

Like the iOS design, icon and amount for kudos, likes and extra athletes. Right bottom of activity
